"""add transfer_method to wallet transactions

Revision ID: 1f5f0453fc5e
Revises: 47211c554bcd
Create Date: 2026-07-29 19:43:19.105910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5f0453fc5e'
down_revision: Union[str, Sequence[str], None] = '47211c554bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('transfer_method', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_transactions', 'transfer_method')
    # ### end Alembic commands ###
