"""add bale_channel_message_id to verification requests

Revision ID: 2171578e5f25
Revises: b4958894c474
Create Date: 2026-07-29 18:59:54.091523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2171578e5f25'
down_revision: Union[str, Sequence[str], None] = 'b4958894c474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('bale_channel_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_requests', 'bale_channel_message_id')
    # ### end Alembic commands ###
