"""add wallet transactions and balance

Revision ID: 47211c554bcd
Revises: 2171578e5f25
Create Date: 2026-07-29 19:24:49.228145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47211c554bcd'
down_revision: Union[str, Sequence[str], None] = '2171578e5f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='transactionstatus'), nullable=False),
    sa.Column('receipt_bale_file_id', sa.String(length=255), nullable=True),
    sa.Column('bale_channel_message_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rejection_reason_id'], ['rejection_reasons.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
