"""add loan account, rate, and request models

Revision ID: a305e5757a77
Revises: dc82bc01a73e
Create Date: 2026-07-30 21:21:16.006502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a305e5757a77'
down_revision: Union[str, Sequence[str], None] = 'dc82bc01a73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_type', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=8), nullable=False),
    sa.Column('installment_months', sa.Integer(), nullable=False),
    sa.Column('rate_per_million', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_type', sa.String(length=32), nullable=False),
    sa.Column('national_id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_type', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.Enum('SELL', 'BUY', name='loanactiontype'), nullable=False),
    sa.Column('point_type', sa.Enum('REAL', 'LEGAL', name='loanpointtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installment_months', sa.Integer(), nullable=False),
    sa.Column('rate_per_million', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recipient_is_self', sa.Boolean(), nullable=False),
    sa.Column('recipient_national_id', sa.String(length=16), nullable=True),
    sa.Column('recipient_full_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_phone_number', sa.String(length=32), nullable=True),
    sa.Column('recipient_account_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='loanrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_requests')
    op.drop_table('loan_accounts')
    op.drop_table('loan_rates')
    # ### end Alembic commands ###
