"""add verification requests and rejection reasons

Revision ID: b4958894c474
Revises: e53a4ba2b860
Create Date: 2026-07-29 13:24:54.396141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4958894c474'
down_revision: Union[str, Sequence[str], None] = 'e53a4ba2b860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejection_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bale_file_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('rejection_reason_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rejection_reason_id'], ['rejection_reasons.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False, server_default='UNVERIFIED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_status')
    op.drop_table('verification_requests')
    op.drop_table('rejection_reasons')
    # ### end Alembic commands ###
