"""add withdrawal request model

Revision ID: bb9ec675e454
Revises: 1f5f0453fc5e
Create Date: 2026-07-29 21:14:27.429145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9ec675e454'
down_revision: Union[str, Sequence[str], None] = '1f5f0453fc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('sheba_number', sa.String(length=32), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_SETTLED', 'SETTLED', 'REJECTED', name='withdrawalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('wallet_transactions', sa.Column('withdrawal_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wallet_transactions', 'withdrawal_requests', ['withdrawal_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_column('wallet_transactions', 'withdrawal_request_id')
    op.drop_table('withdrawal_requests')
    # ### end Alembic commands ###
