"""add unique constraint on loan_account user and bank_type

Revision ID: da3872c4f66e
Revises: a305e5757a77
Create Date: 2026-07-30 21:40:31.158218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3872c4f66e'
down_revision: Union[str, Sequence[str], None] = 'a305e5757a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_loan_account_user_bank', 'loan_accounts', ['user_id', 'bank_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_loan_account_user_bank', 'loan_accounts', type_='unique')
    # ### end Alembic commands ###
