"""add bank account model and link to withdrawal request

Revision ID: dfd3603aa77e
Revises: bb9ec675e454
Create Date: 2026-07-29 21:28:13.538170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd3603aa77e'
down_revision: Union[str, Sequence[str], None] = 'bb9ec675e454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sheba_number', sa.String(length=32), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='bankaccountstatus'), nullable=False),
    sa.Column('rejection_reason_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rejection_reason_id'], ['rejection_reasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('withdrawal_requests', sa.Column('bank_account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'withdrawal_requests', 'bank_accounts', ['bank_account_id'], ['id'])
    op.drop_column('withdrawal_requests', 'bank_name')
    op.drop_column('withdrawal_requests', 'account_holder_name')
    op.drop_column('withdrawal_requests', 'sheba_number')
    op.drop_column('withdrawal_requests', 'card_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal_requests', sa.Column('card_number', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('withdrawal_requests', sa.Column('sheba_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('withdrawal_requests', sa.Column('account_holder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('withdrawal_requests', sa.Column('bank_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'withdrawal_requests', type_='foreignkey')
    op.drop_column('withdrawal_requests', 'bank_account_id')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
