"""add bale_username to users

Revision ID: e53a4ba2b860
Revises: c80aad0f1026
Create Date: 2026-07-28 23:05:55.950527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53a4ba2b860'
down_revision: Union[str, Sequence[str], None] = 'c80aad0f1026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bale_username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'bale_username')
    # ### end Alembic commands ###
